[build-system]
requires = [
    "hatchling>=1.10.0", "jupyter_client"
]
build-backend = "hatchling.build"

[project]
name="magma_kernel"
dynamic = [
    "version",
]
description="A Magma kernel for Jupyter"
authors=[{name = "Edgar Costa", email = "edgarc@mit.edu"}]
license={text = "BSD License"}
requires-python = ">=3.9"
keywords=["magma", "kernel", "jupyter"]
readme = "README.md"
classifiers=[
  "Development Status :: 4 - Beta",
  "Intended Audience :: Science/Research",
  "Topic :: Scientific/Engineering :: Mathematics",
  "License :: OSI Approved :: BSD License",
  "Programming Language :: Python :: 3",
  "Framework :: Jupyter",
]
dependencies = [
    "ipykernel",
    "jupyter_client",
    "pygments",
    "tree-sitter",
    "tree-sitter-magma @ git+https://github.com/edgarcosta/tree-sitter-magma.git",
]

[project.optional-dependencies]
test = ["pytest", "pytest-cov"]

[project.urls]
Homepage = "https://github.com/edgarcosta/magma_kernel"
Repository = "https://github.com/edgarcosta/magma_kernel"
Issues = "https://github.com/edgarcosta/magma_kernel/issues"

[project.entry-points."pygments.lexers"]
magma = "magma_kernel.lexer:MagmaLexer"

[tool.hatch.metadata]
# Allow `tree-sitter-magma @ git+https://...` in [project.dependencies].
allow-direct-references = true

[tool.hatch.version]
path = "magma_kernel/__init__.py"

# Used to call hatch_build.py
[tool.hatch.build.hooks.custom]

[tool.hatch.build.targets.sdist]
include = [
    "/magma_kernel",
    "/hatch_build.py",
]


[tool.hatch.build.targets.wheel.shared-data]
"data_kernelspec/share" = "share"

